markdown: kramdown
highlighter: pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 5
paginate_path: page/:num

blog:
    name: ou_kongli                                                # 博客名称
    description1: 十步杀一人   # 博客描述1
    description2: 千里不留行   # 博客描述2
    description3: 事了拂衣去   # 博客描述3
    description4: 深藏身与名   # 博客描述4
    title:  ou_kongli                                             # 网页标题
    url:   oukongli.github.io                                              # 博客地址
    duoshuo:                                             # 多说ID
    tongji:                                              # 百度统计ID
    qiniu:                                               # 七牛云地址
author:
    name:      ou_kongli                                         # 作者名称
    email:     oukongli(at)gmail.com                                # 邮箱地址
    weibo:      http://weibo.com/p/1005053225252100              # 微博地址
    github:     https://github.com/oukongli                      # GitHub地址
    logo:       /images/logo.jpg                                 # logo地址
    douban:
        name:                                            # 豆瓣地址名称
        key:                                             # 豆瓣API Key